name: Build macOS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        default: 'main'
        required: true
        type: string
      release_tag:
        description: 'tag'
        required: true
        type: string

permissions: {}

jobs:
  build:
    runs-on: macos-latest
    env:
      NUITKA_AssumeYesForDownloads: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        repository: ${{ secrets.PRIVATE_REPO_NAME }}
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        ref: ${{ inputs.branch }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system -r pyproject.toml
        pip install nuitka

    - name: Build App
      run: |
        uv run python scripts/build_macos.py > build_log.txt 2>&1 || (echo "Build Failed! Check local environment." && exit 1)

    - name: Create Zip
      run: |
        cd out
        zip -r "${{ secrets.APP_NAME_EN }}-${{ inputs.release_tag }}-macOS.zip" "${{ secrets.APP_NAME_ZH }}.app" > /dev/null 2>&1

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        repository: ${{ secrets.PRIVATE_REPO_NAME }}
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        tag_name: ${{ inputs.release_tag }}
        files: out/${{ secrets.APP_NAME_EN }}-macOS.zip

    - name: Bark Notification
      if: always()
      run: curl "https://api.day.app/${{ secrets.BARK_KEY }}/macOSBuild/${{ job.status }}"
