name: Build windows

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        default: 'main'
        required: true
        type: string
      release_tag:
        description: 'tag'
        required: true
        type: string
      show_logs:
        description: '是否在控制台显示详细日志'
        required: false
        default: false
        type: boolean

permissions: {}

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NUITKA_AssumeYesForDownloads: 1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        repository: ${{ secrets.PRIVATE_REPO_NAME }}
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        ref: ${{ inputs.branch }}
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        
    - name: Install uv
      shell: cmd
      run: |
        if /I "${{ inputs.show_logs }}"=="true" (
          pip install uv
        ) else (
          pip install uv > NUL 2>&1
        )
        
    - name: Install dependencies
      shell: cmd
      run: |
        if /I "${{ inputs.show_logs }}"=="true" (
          uv sync
        ) else (
          uv sync > NUL 2>&1
        )
        
    - name: Build Windows
      shell: cmd
      run: |
        if /I "${{ inputs.show_logs }}"=="true" (
          uv run python scripts/build_windows.py
        ) else (
          uv run python scripts/build_windows.py > build_windows.log 2>&1 || (type build_windows.log & echo Build Failed & exit /b 1)
        )

    - name: Install Inno Setup
      shell: cmd
      run: |
        if /I "${{ inputs.show_logs }}"=="true" (
          choco install innosetup --no-progress
        ) else (
          choco install innosetup --no-progress > NUL 2>&1
        )

    - name: Build Installer
      shell: cmd
      run: |
        if /I "${{ inputs.show_logs }}"=="true" (
          iscc pack_installer.iss
        ) else (
          iscc pack_installer.iss > build_installer.log 2>&1 || (type build_installer.log & echo Installer Build Failed & exit /b 1)
        )
        
    - name: Create Portable Zip
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path release | Out-Null
        Compress-Archive -Path out/entry.dist -DestinationPath release/${{ secrets.APP_NAME_EN }}-${{ inputs.release_tag }}-Windows-Portable.zip -Force

    - name: Upload to Private Release
      uses: softprops/action-gh-release@v1
      with:
        repository: ${{ secrets.PRIVATE_REPO_NAME }}
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        tag_name: ${{ inputs.release_tag }}
        files: |
          release/*.exe
          release/*.zip

    - name: Bark Notification
      if: always()
      run: curl.exe "https://api.day.app/${{ secrets.BARK_KEY }}/WindowsBuild/${{ job.status }}"
